// Products Data - كامل 33 منتج موزعة على أقسام مختلفة
const productsData = [
    // موازين سوبر ماركت (5 منتجات)
    { id: 1, img: 'scale1.jpeg', images: ['scale1.jpeg','scale2.jpeg','scale3.jpeg'], cat:'موازين سوبر ماركت', name:'ميزان سوبر ماركت احترافي', desc:'مثالي للاستخدام في السوبر ماركت والبقالات', price:850, oldPrice:1100, details:{capacity:'حتى 30 كجم',accuracy:'±5 جرام',display:'شاشة رقمية مزدوجة',power:'كهرباء 220 فولت أو بطارية',material:'بلاستيك ABS عالي الجودة',warranty:'سنتان'}, features:['شاشة مزدوجة للبائع والعميل','حساب السعر الإجمالي تلقائياً','ذاكرة حفظ الأسعار','قابل للشحن','صوت تنبيه عند إتمام الوزن','مناسب للمحلات التجارية']},
    { id: 2, img: 'scale2.jpeg', images: ['scale2.jpeg','scale4.jpeg','scale5.jpeg'], cat:'موازين سوبر ماركت', name:'ميزان سوبر ماركت متطور', desc:'مناسب لجميع الأغراض التجارية', price:950, oldPrice:1200, details:{capacity:'حتى 40 كجم',accuracy:'±2 جرام',display:'شاشة LCD مضيئة',power:'كهرباء أو بطارية',material:'بلاستيك مقوى',warranty:'سنة ونصف'}, features:['سعر ووزن وإجمالي على الشاشة','حفظ حتى 200 صنف','طباعة الفاتورة (اختياري)','توصيل بالكمبيوتر','صفر تلقائي','مناسب للسوبرماركت']},
    { id: 3, img: 'scale3.jpeg', images: ['scale3.jpeg','scale7.jpeg','scale8.jpeg'], cat:'موازين سوبر ماركت', name:'ميزان سوبر ماركت إلكتروني', desc:'للمحلات والأسواق', price:1100, oldPrice:1400, details:{capacity:'حتى 40 كجم',accuracy:'±5 جرام',display:'شاشتان LED',power:'كهرباء 220V',material:'بلاستيك صناعي',warranty:'سنتان'}, features:['شاشة للبائع والعميل','حساب السعر أوتوماتيكي','لوحة أرقام سهلة','صوت تأكيد الوزن','متين وقوي','ضمان قطع الغيار']},
    { id: 4, img: 'scale4.jpeg', images: ['scale4.jpeg','scale1.jpeg','scale9.jpeg'], cat:'موازين سوبر ماركت', name:'ميزان سوبر ماركت للبقالات', desc:'سهل الاستخدام ودقيق', price:780, oldPrice:950, details:{capacity:'حتى 40 كجم',accuracy:'±5 جرام',display:'شاشتان أمامية وخلفية',power:'كهرباء',material:'بلاستيك صناعي متين',warranty:'سنة واحدة'}, features:['شاشتان للراحة','حساب الإجمالي','أزرار كبيرة','صوت تنبيه','سلك طويل','مناسب للبقالات']},
    { id: 5, img: 'scale5.jpeg', images: ['scale5.jpeg','scale3.jpeg','scale7.jpeg'], cat:'موازين سوبر ماركت', name:'ميزان سوبر ماركت ديجيتال', desc:'دقة عالية وأداء موثوق', price:920, oldPrice:1150, details:{capacity:'حتى 35 كجم',accuracy:'±3 جرام',display:'شاشة LED ساطعة',power:'كهرباء',material:'بلاستيك ABS',warranty:'سنتان'}, features:['شاشة واضحة','حساب تلقائي','صوت تنبيه','سهل الاستخدام','متين جداً','ضمان شامل']},
    
    // موازين صناعية (6 منتجات)
    { id: 6, img: 'scale6.jpeg', images: ['scale7.jpeg','scale8.jpeg','scale13.jpeg'], cat:'موازين صناعية', name:'ميزان صناعي ثقيل', desc:'للاستخدام الصناعي والتجاري الثقيل', price:3500, oldPrice:4500, details:{capacity:'حتى 300 كجم',accuracy:'±50 جرام',display:'شاشة LED كبيرة',power:'كهرباء 220 فولت',material:'حديد صلب مع طلاء مقاوم',warranty:'3 سنوات'}, features:['تحمل فائق للأوزان الثقيلة','قاعدة بلاتفورم كبيرة 40×50 سم','مقاوم للصدأ والعوامل الجوية','شهادة معايرة معتمدة','كابل طويل للشاشة','مناسب للمصانع والمستودعات']},
    { id: 7, img: 'scale7.jpeg', images: ['scale8.jpeg','scale3.jpeg','scale13.jpeg'], cat:'موازين صناعية', name:'ميزان صناعي فائق الدقة', desc:'ضمان طويل وخدمة ما بعد البيع', price:4200, oldPrice:5500, details:{capacity:'حتى 500 كجم',accuracy:'±100 جرام',display:'شاشة رقمية LED',power:'كهرباء 220 فولت',material:'حديد مجلفن',warranty:'5 سنوات'}, features:['مصمم للاستخدام الشاق','معايرة دقيقة من المصنع','قاعدة 60×80 سم','يتحمل الاستخدام المستمر','صيانة دورية مجانية','قطع غيار متوفرة دائماً']},
    { id: 8, img: 'scale8.jpeg', images: ['scale9.jpeg','scale1.jpeg','scale2.jpeg'], cat:'موازين صناعية', name:'ميزان صناعي للمصانع', desc:'تحمل أوزان كبيرة بدقة عالية', price:5500, oldPrice:7000, details:{capacity:'حتى 1 طن',accuracy:'±200 جرام',display:'شاشة LED صناعية',power:'كهرباء صناعي 380V',material:'حديد صلب مجلفن',warranty:'5 سنوات'}, features:['تحمل طن كامل','قاعدة بلاتفورم 100×120 سم','مقاوم للصدمات','معايرة صناعية','كابل 5 متر','صيانة سنوية مجانية']},
    { id: 9, img: 'scale9.jpeg', images: ['scale8.jpeg','scale3.jpeg','scale13.jpeg'], cat:'موازين صناعية', name:'ميزان صناعي بلاتفورم', desc:'قاعدة كبيرة وثابتة', price:3200, oldPrice:4000, details:{capacity:'حتى 300 كجم',accuracy:'±50 جرام',display:'شاشة رقمية LED',power:'كهرباء 220V',material:'حديد مطلي',warranty:'3 سنوات'}, features:['بلاتفورم 50×60 سم','قاعدة قوية ومستقرة','عجلات للحركة','كابل 3 متر','معايرة دقيقة','للمستودعات والمصانع']},
    { id: 10, img: 'scale10.jpeg', images: ['scale9.jpeg','scale1.jpeg','scale2.jpeg'], cat:'موازين صناعية', name:'ميزان صناعي ثقيل جداً', desc:'للأوزان الكبيرة والثقيلة', price:6200, oldPrice:8000, details:{capacity:'حتى 2 طن',accuracy:'±500 جرام',display:'شاشة LED صناعية كبيرة',power:'كهرباء صناعي',material:'حديد صلب مقوى',warranty:'7 سنوات'}, features:['يتحمل 2 طن','بلاتفورم 150×150 سم','حساسات هيدروليكية','مقاوم للعوامل الجوية','شهادة معايرة دولية','صيانة شاملة']},
    { id: 11, img: 'scale11.jpeg', images: ['scale10.jpeg','scale1.jpeg','scale2.jpeg'], cat:'موازين صناعية', name:'ميزان صناعي متين', desc:'تحمل كبير واستخدام طويل', price:6800, oldPrice:8500, details:{capacity:'حتى 4 طن',accuracy:'±500 جرام',display:'شاشة LED صناعية',power:'كهرباء صناعي',material:'حديد صلب',warranty:'5 سنوات'}, features:['تحمل 4 طن','بلاتفورم 200×200 سم','حساسات متطورة','صيانة سنوية','مقاوم للصدمات','معايرة دولية']},
    
    // موازين رقمية (5 منتجات)
    { id: 12, img: 'scale12.jpeg', images: ['scale11.jpeg','scale1.jpeg','scale2.jpeg'], cat:'موازين رقمية', name:'ميزان رقمي للمطبخ', desc:'ميزان رقمي عالي الدقة', price:450, oldPrice:600, details:{capacity:'حتى 5 كجم',accuracy:'±1 جرام',display:'شاشة LCD كبيرة',power:'بطاريات AAA',material:'ستانلس ستيل',warranty:'سنة واحدة'}, features:['دقة عالية في القياس','سهل التنظيف','وظيفة الصفر التلقائي','تحويل بين الوحدات','إيقاف تلقائي','قاعدة مانعة للانزلاق']},
    { id: 13, img: 'scale13.jpeg', images: ['scale12.jpeg','scale2.jpeg','scale5.jpeg'], cat:'موازين رقمية', name:'ميزان رقمي متقدم', desc:'شاشة كبيرة وقراءة واضحة', price:520, oldPrice:700, details:{capacity:'حتى 7 كجم',accuracy:'±1 جرام',display:'شاشة LCD XXL',power:'بطاريات قابلة للشحن',material:'ستانلس ستيل',warranty:'سنة ونصف'}, features:['شاشة كبيرة جداً','إضاءة خلفية قوية','بطارية قابلة للشحن','قراءة من بعيد','صوت تنبيه','تصميم أنيق']},
    { id: 14, img: 'scale14.jpeg', images: ['scale13.jpeg','scale3.jpeg','scale7.jpeg'], cat:'موازين رقمية', name:'ميزان رقمي احترافي', desc:'دقة ممتازة وسهولة استخدام', price:480, oldPrice:650, details:{capacity:'حتى 10 كجم',accuracy:'±1 جرام',display:'شاشة LCD',power:'بطاريات AAA',material:'بلاستيك متين',warranty:'سنة واحدة'}, features:['دقة عالية','تصميم عصري','سهل الاستخدام','إيقاف تلقائي','تحويل وحدات','مثالي للمنزل']},
    { id: 15, img: 'scale15.jpeg', images: ['scale14.jpeg','scale1.jpeg','scale4.jpeg'], cat:'موازين رقمية', name:'ميزان رقمي مطبخ', desc:'لكل احتياجات المطبخ', price:420, oldPrice:580, details:{capacity:'حتى 5 كجم',accuracy:'±1 جرام',display:'شاشة LCD مضيئة',power:'بطاريات AAA',material:'ستانلس ستيل',warranty:'سنة واحدة'}, features:['سطح واسع','سهل التنظيف','دقة ممتازة','تحويل وحدات','تصميم أنيق','مثالي للخبز']},
    { id: 16, img: 'scale16.jpeg', images: ['scale15.jpeg','scale9.jpeg','scale10.jpeg'], cat:'موازين رقمية', name:'ميزان رقمي منزلي', desc:'دقة وراحة في الاستخدام', price:380, oldPrice:520, details:{capacity:'حتى 8 كجم',accuracy:'±1 جرام',display:'شاشة LCD',power:'بطاريات AAA',material:'بلاستيك',warranty:'سنة واحدة'}, features:['سهل الاستخدام','خفيف الوزن','دقة عالية','تصميم عصري','إيقاف تلقائي','مثالي للمطبخ']},
    
    // موازين شخصية (5 منتجات)
    { id: 17, img: 'scale17.jpeg', images: ['scale16.jpeg','scale1.jpeg','scale10.jpeg'], cat:'موازين شخصية', name:'ميزان قياس الوزن الشخصي', desc:'تصميم أنيق وقراءات دقيقة', price:420, oldPrice:600, details:{capacity:'حتى 180 كجم',accuracy:'±100 جرام',display:'شاشة رقمية كبيرة',power:'بطاريات AAA',material:'زجاج مقسى',warranty:'سنتان'}, features:['سطح زجاجي أنيق','تشغيل تلقائي','إطفاء أوتوماتيكي','مضاد للانزلاق','أرقام كبيرة واضحة','تصميمات متنوعة']},
    { id: 18, img: 'scale18.jpeg', images: ['scale17.jpeg','scale1.jpeg','scale4.jpeg'], cat:'موازين شخصية', name:'ميزان شخصي إلكتروني', desc:'تصميم عصري ومتين', price:390, oldPrice:550, details:{capacity:'حتى 180 كجم',accuracy:'±100 جرام',display:'شاشة LCD',power:'بطاريات AAA',material:'زجاج مقوى',warranty:'سنة واحدة'}, features:['سطح زجاجي مقاوم','إيقاف تلقائي','دقة ممتازة','أرقام واضحة','خفيف وسهل النقل','تصميم عصري']},
    { id: 19, img: 'scale19.jpeg', images: ['scale19.jpeg','scale3.jpeg','scale13.jpeg'], cat:'موازين شخصية', name:'ميزان شخصي ذكي', desc:'متابعة الوزن والصحة', price:520, oldPrice:700, details:{capacity:'حتى 200 كجم',accuracy:'±100 جرام',display:'شاشة رقمية ذكية',power:'بطاريات AAA',material:'زجاج مقاوم',warranty:'سنة واحدة'}, features:['تتبع الوزن','متابعة BMI','تصميم عصري','سطح مقاوم للانزلاق','إشعارات ذكية','خفيف وسهل التخزين']},
    { id: 20, img: 'scale20.jpeg', images: ['scale20.jpeg','scale4.jpeg','scale14.jpeg'], cat:'موازين شخصية', name:'ميزان شخصي رقمي', desc:'سهل الاستخدام وأنيق', price:350, oldPrice:490, details:{capacity:'حتى 180 كجم',accuracy:'±100 جرام',display:'شاشة LCD كبيرة',power:'بطاريات AAA',material:'زجاج مقسى',warranty:'سنة واحدة'}, features:['قراءة فورية','تصميم أنيق','سطح مانع للانزلاق','إيقاف تلقائي','خفيف الوزن','سهل التخزين']},
    { id: 21, img: 'scale21.jpeg', images: ['scale21.jpeg','scale1.jpeg','scale11.jpeg'], cat:'موازين شخصية', name:'ميزان شخصي عصري', desc:'دقة عالية وتصميم جميل', price:410, oldPrice:580, details:{capacity:'حتى 200 كجم',accuracy:'±100 جرام',display:'شاشة رقمية',power:'بطاريات AAA',material:'زجاج',warranty:'سنة واحدة'}, features:['شاشة واضحة','سطح زجاجي','تشغيل فوري','إيقاف تلقائي','تصميم راقي','مثالي للمنزل']},
    
    // موازين دقيقة (5 منتجات)
    { id: 22, img: 'scale22.jpeg', images: ['scale22.jpeg','scale2.jpeg','scale12.jpeg'], cat:'موازين دقيقة', name:'ميزان دقيق للمعادن الثمينة', desc:'دقة عالية جداً للذهب والفضة', price:750, oldPrice:950, details:{capacity:'حتى 500 جرام',accuracy:'±0.01 جرام',display:'شاشة LED فائقة الوضوح',power:'بطاريات AAA',material:'ستانلس ستيل مصقول',warranty:'سنتان'}, features:['دقة 0.01 جرام','معايرة تلقائية','وحدات متعددة (جم/قيراط/أونصة)','غطاء حماية زجاجي','مثالي لمحلات الذهب','شهادة معايرة معتمدة']},
    { id: 23, img: 'scale23.jpeg', images: ['scale23.jpeg','scale3.jpeg','scale8.jpeg'], cat:'موازين دقيقة', name:'ميزان دقيق مختبري', desc:'للمختبرات والصيدليات', price:1200, oldPrice:1500, details:{capacity:'حتى 2 كجم',accuracy:'±0.01 جرام',display:'شاشة LED دقيقة',power:'بطاريات AAA',material:'ستانلس ستيل عالي الجودة',warranty:'سنتان'}, features:['معايرة دقيقة','وحدات متعددة','سطح مقاوم للمواد الكيميائية','سهل التنظيف','شهادة جودة','مثالي للمختبرات']},
    { id: 25, img: 'scale25.jpeg', images: ['scale25.jpeg','scale5.jpeg','scale10.jpeg'], cat:'موازين دقيقة', name:'ميزان طبي للصيدليات', desc:'معتمد ومطابق للمواصفات', price:1800, oldPrice:2200, details:{capacity:'حتى 200 جرام',accuracy:'±0.001 جرام',display:'شاشة رقمية طبية',power:'كهرباء',material:'ستانلس ستيل طبي',warranty:'3 سنوات'}, features:['دقة 0.001 جرام','معتمد من وزارة الصحة','معايرة طبية','غرفة وزن زجاجية','مقاومة للمواد الكيميائية','شهادة ISO']},
    { id: 26, img: 'scale26.jpeg', images: ['scale26.jpeg','scale6.jpeg','scale11.jpeg'], cat:'موازين دقيقة', name:'ميزان دقيق للذهب', desc:'دقة فائقة لمحلات الذهب', price:820, oldPrice:1050, details:{capacity:'حتى 1 كجم',accuracy:'±0.01 جرام',display:'شاشة LED',power:'بطاريات AAA',material:'ستانلس ستيل',warranty:'سنتان'}, features:['دقة 0.01 جرام','وحدات متعددة','معايرة دقيقة','غطاء حماية','مثالي للذهب والفضة','شهادة معايرة']},
    
    // موازين إلكترونية (5 منتجات)
    { id: 27, img: 'scale27.jpeg', images: ['scale27.jpeg','scale7.jpeg','scale16.jpeg'], cat:'موازين إلكترونية', name:'ميزان إلكتروني احترافي', desc:'تقنية حديثة ودقة عالية', price:980, oldPrice:1250, details:{capacity:'حتى 25 كجم',accuracy:'±2 جرام',display:'شاشة LCD ملونة',power:'بطارية ليثيوم قابلة للشحن',material:'ألومنيوم خفيف',warranty:'سنتان'}, features:['تقنية حساسات ذكية','شحن سريع USB','واجهة سهلة','ذاكرة آخر 50 عملية','صوت وإضاءة تنبيه','تصميم عصري']},
    { id: 28, img: 'scale28.jpeg', images: ['scale28.jpeg','scale8.jpeg','scale17.jpeg'], cat:'موازين إلكترونية', name:'ميزان إلكتروني متعدد الوظائف', desc:'للاستخدام المنزلي والمكاتب', price:680, oldPrice:900, details:{capacity:'حتى 20 كجم',accuracy:'±2 جرام',display:'شاشة LCD ملونة',power:'بطاريات AAA',material:'بلاستيك متين',warranty:'سنة ونصف'}, features:['أداء سريع','شاشة كبيرة','تبديل وحدات سريع','تحويل الوزن والسعر','صوت تنبيه','سهل الاستخدام']},
    { id: 29, img: 'scale29.jpeg', images: ['scale29.jpeg','scale9.jpeg','scale18.jpeg'], cat:'موازين إلكترونية', name:'ميزان إلكتروني دقيق', desc:'مثالي للاستخدام اليومي', price:720, oldPrice:920, details:{capacity:'حتى 30 كجم',accuracy:'±3 جرام',display:'شاشة LED',power:'بطارية قابلة للشحن',material:'بلاستيك ABS',warranty:'سنة ونصف'}, features:['شاشة واضحة','بطارية تدوم طويلاً','تحويل وحدات','صوت تنبيه','تصميم عملي','سهل الاستخدام']},
    { id: 30, img: 'scale30.jpeg', images: ['scale30.jpeg','scale10.jpeg','scale19.jpeg'], cat:'موازين إلكترونية', name:'ميزان إلكتروني منزلي', desc:'دقة وسهولة في الاستخدام', price:620, oldPrice:820, details:{capacity:'حتى 15 كجم',accuracy:'±2 جرام',display:'شاشة LCD',power:'بطاريات AAA',material:'بلاستيك',warranty:'سنة واحدة'}, features:['شاشة واضحة','خفيف الوزن','دقة جيدة','تحويل وحدات','تصميم بسيط','مثالي للمنزل']},
    { id: 31, img: 'scale31.jpeg', images: ['scale31.jpeg','scale11.jpeg','scale20.jpeg'], cat:'موازين إلكترونية', name:'ميزان إلكتروني عصري', desc:'تصميم أنيق وأداء ممتاز', price:790, oldPrice:1020, details:{capacity:'حتى 28 كجم',accuracy:'±2 جرام',display:'شاشة LED ملونة',power:'بطارية قابلة للشحن',material:'ألومنيوم',warranty:'سنتان'}, features:['شاشة ملونة','شحن USB','واجهة سهلة','ذاكرة البيانات','تصميم عصري','ضمان شامل']},
    
    // موازين متنوعة إضافية
    { id: 32, img: 'scale32.jpeg', images: ['scale32.jpeg','scale12.jpeg','scale21.jpeg'], cat:'موازين صناعية', name:'ميزان صناعي متين', desc:'تحمل كبير واستخدام طويل', price:6800, oldPrice:8500, details:{capacity:'حتى 4 طن',accuracy:'±500 جرام',display:'شاشة LED صناعية',power:'كهرباء صناعي',material:'حديد صلب',warranty:'5 سنوات'}, features:['تحمل 4 طن','بلاتفورم 200×200 سم','حساسات متطورة','صيانة سنوية','مقاوم للصدمات','معايرة دولية']},
    { id: 33, img: 'scale33.jpeg', images: ['scale33.jpeg','scale13.jpeg','scale22.jpeg'], cat:'موازين رقمية', name:'ميزان رقمي كومباكت', desc:'دقة وراحة في الاستخدام', price:480, oldPrice:650, details:{capacity:'حتى 12 كجم',accuracy:'±1 جرام',display:'شاشة LCD',power:'بطاريات AAA',material:'بلاستيك متين',warranty:'سنة واحدة'}, features:['حجم صغير','إيقاف تلقائي','أرقام واضحة','تصميم عصري','خفيف وسهل الحمل','مثالي للمنزل']}
];

// دوال مساعدة
function getProductById(id) {
    return productsData.find(p => p.id === parseInt(id));
}
function getAllProducts() {
    return productsData;
}